Updating recycler view
csbast/loginAndRegisterApp pull request #4
Opened 2021-07-06 23:49 UTC by csbast

Apenas para revisão!

2021-07-07 01:36 UTC, rsalomao2 requested changes

2021-07-07 01:36 UTC, rsalomao2 commented on app/src/main/java/com/example/android/week0/adapter/UsersAdapters.kt
> +            view.findNavController().navigate(action)
A navegação é de responsabilidade do Fragment/Acitivty (lê-se View)

2021-07-07 01:36 UTC, rsalomao2 commented on app/src/main/java/com/example/android/week0/fragments/Deletar.kt
> -package com.example.android.week0.fragments
Deletar!

2021-07-07 01:36 UTC, rsalomao2 commented on app/src/main/java/com/example/android/week0/model/User.kt
> +    )
Linha

2021-07-07 01:36 UTC, rsalomao2 commented on app/src/main/res/layout/fragment_users_detail.xml
> +</layout>
Linha

2021-07-07 01:36 UTC, rsalomao2 commented on app/src/main/res/values/strings.xml
>  </resources>
Linha

2021-07-14 00:03 UTC, csbast reviewed
Alterações feitas, linhas adicionadas ao final dos arquivos que estavam faltando.

2021-07-14 00:54 UTC, rsalomao2 approved these changes
Gj man 🍪

2021-07-14 00:54 UTC, merged